### ISSUE TITLE
Could not pass event PlayerQuitEvent

### ISSUE THREAD

**Issue by Daedmon** [M0diis/SRV-Cron#1]
Could not pass event PlayerQuitEvent. (https://pastebin.com/bt08ewbv)

> To reproduce:
> 
> 1. Install plugin & reboot server.
> 2. Join & leave server.

**Comment by M0diis** [comment]
Thank you for the report, I'll look into it ASAP.

**Comment by M0diis** [comment]
Should be fixed as of latest commit.
