### ISSUE TITLE
Plugin v2.8.0 shows as v2.7.0

### ISSUE THREAD

**Issue by Daedmon** [M0diis/SRV-Cron#2]
Plugin v2.8.0 shows as v2.7.0
Latest version is installed, I'm sure.
(https://pastebin.com/bt08ewbv)

**Comment by M0diis** [comment]
Duplicate #1

**Comment by M0diis** [comment]
Mismatched the issues.

I'll fix it in the new release.

**Comment by M0diis** [comment]
Should be fixed as of latest commit.
